### ISSUE TITLE
i got his entire config when i logged his friend 

### ISSUE THREAD

**Issue by OlDestiny** [HausemasterIssue/2b2t-Future-Config#2]
[wao config ewww.zip](https://github.com/HausemasterIssue/future-autocrystal-config/files/7662330/wao.config.ewww.zip)

**Comment by HausemasterIssue** [comment]
that config is shit, and token logging is cringe bro.

**Comment by OlDestiny** [comment]
indeed

**Comment by master7720** [comment]
> 

…..

**Comment by master7720** [comment]
browser data and accounts are straight up going too far. get rid of it please. - HausemasterIssue

**Comment by HausemasterIssue** [comment]
Selling that quote as a NFT gonna get loads of funds
